server:
  port: 8001

spring:
  application:
    name: CLOUD-COMPUTE-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: compute8001
    prefer-ip-address: true
